_data_hub_batch_import_data_object_admin:
    resource: "@PimcoreDataHubBatchImportBundle/Controller/ConfigDataObjectController.php"
    type:     annotation
    options:
        expose: true

_data_hub_batch_import_data_object_push:
    resource: "@PimcoreDataHubBatchImportBundle/Controller/PushImportController.php"
    type:     annotation


_data_hub_batch_import_data_object_debug:
    resource: "@PimcoreDataHubBatchImportBundle/Controller/DefaultController.php"
    type:     annotation